CREATE TABLE [dbo].[import_CSV_2] (
  [Serial Number (asset_Serial_number)] [nvarchar](50) NULL,
  [Alternate hostname] [nvarchar](50) NULL,
  [State] [nvarchar](50) NULL,
  [Substate] [nvarchar](50) NULL,
  [Model Category (asset_Family)] [nvarchar](50) NULL,
  [CI type (asset_Class)] [nvarchar](50) NULL,
  [Model specification (asset_Subclass)] [nvarchar](50) NULL,
  [Last Login User] [nvarchar](50) NULL,
  [Recurrent Login Count] [int] NULL,
  [Recurrent Login User] [nvarchar](50) NULL,
  [Site Category] [nvarchar](50) NULL,
  [User Location (user_location_Name)] [nvarchar](100) NULL,
  [Name (asset_contact_LastName)] [nvarchar](50) NULL,
  [First name] [nvarchar](50) NULL,
  [Last name] [nvarchar](50) NULL,
  [User active (asset_contact_inactive)] [nvarchar](50) NULL,
  [Model name (Model name)] [nvarchar](100) NULL,
  [Custom Update (Last IBM update)] [nvarchar](100) NULL,
  [Status update (SN Status change)] [nvarchar](50) NULL,
  [Certification (Certificazione)] [nvarchar](50) NULL,
  [Model number (Model number)] [nvarchar](50) NULL,
  [User Type (asset_contact_Type)] [nvarchar](50) NULL,
  [Assigned to] [nvarchar](50) NULL,
  [User Subtype (Contact_Subtype)] [nvarchar](50) NULL,
  [Company (contact_Company_Name)] [nvarchar](50) NULL,
  [Company work for (contact_company_distacco)] [nvarchar](50) NULL,
  [Employee/Contact Number (asset_contact_identifier)] [nvarchar](50) NULL,
  [Agency Code] [nvarchar](50) NULL,
  [Asset Location (asset_location_Name)] [nvarchar](50) NULL,
  [Street (asset_location_Address)] [nvarchar](100) NULL,
  [City (asset_location_City)] [nvarchar](50) NULL,
  [Most recent discovery (asset_uam_rundate)] [nvarchar](50) NULL,
  [Reconciliation Date (Riconcilia se data)] [nvarchar](50) NULL,
  [Operating System (asset_Operating_System)] [nvarchar](50) NULL,
  [RAM (MB) (asset_uam_memory)] [nvarchar](50) NULL,
  [CPU type (asset_uam_cpu_type)] [nvarchar](50) NULL,
  [Purchased (asset_Acquire_Date)] [nvarchar](50) NULL,
  [Due (Obsoleto_Dal)] [nvarchar](50) NULL,
  [Owner company] [nvarchar](100) NULL,
  [IP Address] [nvarchar](50) NULL,
  [Email] [nvarchar](100) NULL,
  [Phone] [nvarchar](100) NULL,
  [Mobile phone] [nvarchar](50) NULL,
  [Hierarchical department] [nvarchar](100) NULL,
  [ID] [nvarchar](50) NULL,
  [Company code] [nvarchar](50) NULL,
  [Owner group] [nvarchar](50) NULL,
  [CI legacy ID] [nvarchar](50) NULL,
  [Last Login Date] [nvarchar](100) NULL,
  [Asset] [nvarchar](100) NULL,
  [GL account] [nvarchar](100) NULL,
  [Warranty expiration] [nvarchar](100) NULL,
  [CB indicator] [nvarchar](100) NULL,
  [PoWeb] [nvarchar](100) NULL,
  [Order received] [nvarchar](100) NULL,
  [User ID] [nvarchar](50) NULL,
  [Usage Code] [nvarchar](50) NULL
)
ON [PRIMARY]
GO